import Breadchumb from "@/components/molecules/Section/Breadchumb";
import Header from "@/components/organisms/Header";
import MainProduct from "@/components/organisms/MainProduct";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";

type Props = {};

const index = (props: Props) => {
  return (
    <>
      <Head>
        <title>Kentara | Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Breadchumb />
      <MainProduct />
    </>
  );
};

export default index;
