import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/organisms/Header";

import slide1 from "/public/img/slide1.jpg";
import slide2 from "/public/img/slide2.jpg";
import MainSlider from "@/components/organisms/MainSlider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kentara | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainSlider />
    </>
  );
}
