import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/organisms/Header";
import MainSlider from "@/components/organisms/MainSlider";
import FeaturedProducts from "@/components/organisms/FeaturedProducts";
import NewCollection from "@/components/organisms/NewCollection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kentara | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainSlider />
      <FeaturedProducts />
      <NewCollection />
    </>
  );
}
