import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { FaBeer } from "react-icons/fa";
import Header from "@/components/organisms/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kentara | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  );
}
